export const PRACTICE_AREAS = [
  {
    id: "corporate",
    num: "01",
    title: "Corporate & Commercial",
    short: "Litigation, ADR, IP, and the company-secretarial work that quietly powers Nigerian business.",
    long: "We have represented clients in all superior courts of record in Nigeria, resolving commercial disputes timeously — often using the Case Management Conference to draw up innovative settlements between our clients and their counterparties. We also serve as company secretary to a range of organisations, with statutory filings handled to a turnaround time we continue to set, and break, the record on.",
    bullets: [
      "Construction, environmental and contractual disputes",
      "Intellectual property — registration, renewal & enforcement",
      "Debt recovery, admiralty & general commercial litigation",
      "Alternative Dispute Resolution",
      "Company-secretarial services & statutory filings",
    ],
  },
  {
    id: "estate",
    num: "02",
    title: "Estate Planning & Conveyancing",
    short: "Pace-setting real estate counsel across Lagos, Abuja and Ogun State.",
    long: "We have been consistently adjudged as pace setters in real-estate transactions. Our team leverages numerous contacts at the Lands Registry, energy, and an in-depth practical knowledge of the Lagos, Abuja and Ogun property markets to provide perfection of title and high-level real-estate investigation services with an unrivalled turnaround time. We have developed novel agreements registered at the Lands Registry and the Ministry of Justice — notably a Bill of Sale through which moveable assets of our clients were securitised.",
    bullets: [
      "Perfection of title across Lagos, Abuja & Ogun",
      "In-depth land due diligence",
      "Real-estate investigation",
      "Novel registered instruments (incl. Bill of Sale)",
      "Conveyancing & estate planning",
    ],
  },
  {
    id: "tech",
    num: "03",
    title: "Information Technology Advisory",
    short: "VAS, payment switching, and the Nigerian regulatory perimeter for digital services.",
    long: "Our firm acts for a Value Added Service Company (VAS), drafting agreements between our client and telecommunications operators across Africa, and with the artistes whose content runs on its platform. We have developed operational codes aligned with the Nigerian Communications Commission Act, and recently obtained a lottery licence enabling our client's mobile sports-lottery platform. We also represent a major Nigerian electronic-payments provider — and were germane in obtaining its CBN licence as a Payment Terminal Service Provider — and are currently advising a payment-switching company through its CBN licensing process.",
    bullets: [
      "VAS & telecommunications agreements",
      "NCC operational-code development",
      "Lottery & gaming licensing",
      "CBN PTSP & switching licence applications",
      "Cross-border deployment in Africa",
    ],
  },
  {
    id: "tax",
    num: "04",
    title: "Taxation Advisory",
    short: "A grey but germane area of law — handled by a chartered tax team.",
    long: "Our tax team is made up of skilled and knowledgeable professionals. The team lead is an Associate Member of the Chartered Institute of Taxation of Nigeria, having passed all requisite stages of the professional certification examination, and gained practical experience at the Lagos State Internal Revenue Service — and is regularly engaged by tax authorities on questions of tax law. His Master's dissertation focused on Transfer Pricing. Most recently, we were part of a team that represented a multinational at the Tax Appeal Tribunal in a dispute against the Federal Inland Revenue Service.",
    bullets: [
      "Transaction tax & advisory",
      "Tax Appeal Tribunal representation",
      "FIRS & state revenue disputes",
      "Transfer pricing",
      "Personal & corporate tax planning",
    ],
  },
];

export const TEAM = [
  {
    id: "oj",
    name: "Olanrewaju Jolaoso",
    role: "Team Lead",
    practice: ["corporate", "estate", "tech", "tax"],
    location: "Lagos",
    bar: "—",
    education: ["Master’s Degree, Tax Law/Taxation, University of Lagos"],
    bio: "Olanrewaju leads Prag's commercial and tax practice. His work spans commercial and tax dispute resolution, corporate legal advisory, real-estate transactions, and electronic-payment licensing and advisory. He has led the Prag team since March 2015.",
    cases: [
      "Member, Nigerian Bar Association",
      "Associate, Chartered Institute of Arbitrators (UK & Nigeria)",
      "Member, Professional Negotiators & Mediators of Nigeria",
      "Associate, Chartered Institute of Taxation of Nigeria",
      "Member, International Bar Association",
      "Member, Institute of Chartered Secretaries & Administrators (Nigeria)",
      "Member, Financial Services Lawyers Association (UK)",
    ],
    linkedin: "https://www.linkedin.com/in/olanrewaju-jolaoso-a-ciarb-acis-fcti-9a33b566/",
  },
  {
    id: "as",
    name: "Abioye Sokunbi",
    role: "Partner",
    practice: ["corporate", "estate"],
    location: "Lagos",
    bar: "—",
    education: ["LL.B, Olabisi Onabanjo University", "MSc, Nottingham Business School (UK)"],
    bio: "Abioye has over ten years' legal experience spanning Real Estate, Private Equity, E-commerce and Manufacturing. She began her career as an Associate at Abraham & Co. (Solicitors and Advocates) before moving on to Verod Capital, where she managed several private-equity portfolio companies. Her areas of expertise are Corporate and Commercial Law, Private Equity, Real Estate and E-commerce. Abioye currently sits on the board of several companies — including Vapo Africa, NACK and Solar World — as Company Secretary.",
    cases: [
      "Member, Nigerian Bar Association",
      "Member, Institute of Chartered Secretaries and Administrators (UK)",
    ],
  },
  {
    id: "to",
    name: "Temitope Odeyinka",
    role: "Associate",
    practice: ["corporate"],
    location: "Lagos",
    bar: "2016",
    education: [
      "LL.B, Faculty of Law, University of Lagos (2015)",
      "BL, Nigerian Law School (called to bar 2016)",
    ],
    bio: "Temitope graduated from the Faculty of Law, University of Lagos, in 2015 and was called to the Nigerian Bar in 2016. She has gained legal experience from top-tier law firms through internships and the mandatory NYSC programme, and has a strong working knowledge of Corporate & Commercial Law. She has appeared in a myriad of courts of superior record to argue contentious matters.",
    cases: [
      "Member, Nigerian Bar Association",
      "Student Member, Institute of Chartered Secretaries and Administrators",
    ],
  },
  {
    id: "obo",
    name: "Oluwatimilehin B. Omotayo",
    role: "Associate",
    practice: ["corporate"],
    location: "Lagos",
    bar: "2019",
    education: ["B.L, Nigerian Law School (2019)", "LL.B, Ahmadu Bello University (2018)"],
    bio: "Oluwatimilehin is a Legal Associate at Prag, where she has worked since October 2020. She previously served in the Civil Litigation Department of the Lagos State Ministry of Justice. Her interests include dispute resolution, legal research and the detailed execution of client instructions.",
    cases: ["Associate Member, Institute of Chartered Mediators and Conciliators"],
    linkedin: "https://www.linkedin.com/in/oluwatimilehin-b-omotayo-b50ab1162/",
    needsVerification: true,
  },
  {
    id: "oa",
    name: "Omolade Ajila",
    role: "Associate",
    practice: ["corporate"],
    location: "Lagos",
    bar: "2015",
    education: ["LL.B, Obafemi Awolowo University (2013)"],
    bio: "Omolade is an Associate at Prag with experience in litigation, debt recovery and company-secretarial work. Before joining the firm in December 2018, she practised with P.I. Oye & Associates in Abuja. She has a particular professional interest in company secretarial practice.",
    cases: ["Litigation and debt recovery", "Company-secretarial practice"],
    linkedin: "https://www.linkedin.com/in/omolade-ajila-a66407146/",
    needsVerification: true,
  },
  {
    id: "aa",
    name: "Abisoye (Josephine) Ajayi",
    role: "Legal Associate",
    practice: ["corporate", "estate"],
    location: "Lagos",
    bar: "",
    education: ["LL.B, Obafemi Awolowo University (2021)"],
    bio: "Abisoye is a Legal Associate in Prag's Lagos office. Her experience includes civil and commercial disputes, legal research and advisory work, debt recovery, property documentation, real-estate due diligence and title verification. She joined the firm in November 2025.",
    cases: ["Civil and commercial dispute resolution", "Property due diligence and title verification", "Associate, Institute of Chartered Mediators and Conciliators"],
    linkedin: "https://www.linkedin.com/in/abisoye-ajayi/",
    needsVerification: true,
  },
];

export const ROLES = [
  { id: "r1", title: "Associate, Corporate & Commercial", team: "Corporate / Commercial", type: "Full-time", location: "Lagos" },
  { id: "r2", title: "Associate, Real Estate", team: "Estate Planning & Conveyancing", type: "Full-time", location: "Lagos" },
  { id: "r3", title: "Associate, Disputes", team: "Corporate Litigation & ADR", type: "Full-time", location: "Lagos" },
  { id: "r4", title: "Trainee Solicitor", team: "Rotational", type: "Trainee", location: "Lagos / Abuja" },
  { id: "r5", title: "Tax Counsel", team: "Taxation Advisory", type: "Full-time", location: "Abuja" },
  { id: "r6", title: "IT Advisory Counsel", team: "Information Technology Advisory", type: "Full-time", location: "Lagos" },
];

export const STATS = [
  { num: "14", em: "+", label: "Years advising in Nigeria" },
  { num: "4", em: "", label: "Practice areas" },
  { num: "4", em: "", label: "Offices · Lagos · Abuja · Oyo · Ogun" },
  { num: "1", em: "st", label: "For turnaround time" },
];

export const VALUES = [
  { num: "01", title: "Pragmatic", body: "Legal answers framed as business decisions. We tell you what we'd do — and why." },
  { num: "02", title: "Precise", body: "We sweat the small print. Every comma, every cross-reference, every regulator." },
  { num: "03", title: "Principled", body: "We turn down work that doesn't fit. Long careers depend on it." },
  { num: "04", title: "Present", body: "Senior lawyers on every matter. No bait-and-switch staffing." },
];

export const TIMELINE = [
  { year: "2011", title: "Founded", body: "Prag opens its doors with one stubborn idea — that legal advice is most valuable when it is pragmatic." },
  { year: "2014", title: "Real-estate practice formalised", body: "We codify the conveyancing work we'd been doing into a dedicated team and become known for unrivalled turnaround on perfection of title." },
  { year: "2017", title: "Abuja office opens", body: "Federal capital presence to better serve regulatory and real-estate clients across the FCT." },
  { year: "2020", title: "IT Advisory desk", body: "We are retained by a leading VAS company and act on a CBN PTSP licence — the IT advisory practice becomes a standalone offering." },
  { year: "2023", title: "Oyo & Ogun offices", body: "Ibadan and Sango locations open, anchoring the firm's growing South-West real-estate and corporate footprint." },
  { year: "2026", title: "Fifteen years on", body: "Same convictions, deeper bench, four offices, and a client roster that travels with us." },
];

export const INSIGHTS = [
  {
    id: "cbn-ptsp",
    category: "Fintech & Payments",
    date: "12 June 2026",
    read: "6 min read",
    author: "Olanrewaju Jolaoso",
    title: "The CBN's revised licensing perimeter — what payment companies should do now",
    excerpt: "The Central Bank's tightening of the PTSP and switching categories rewards firms that treat licensing as a design constraint, not an afterthought. A practical reading for founders and general counsel.",
    image: "assets/photo-lagos.png",
    feature: true,
  },
  {
    id: "perfection-title",
    category: "Real Estate",
    date: "28 May 2026",
    read: "5 min read",
    author: "Abioye Sokunbi",
    title: "Perfection of title in Lagos: where the delays actually happen",
    excerpt: "Most title timelines fail at three predictable points. A field guide to governor's consent, the Lands Registry, and the documents that quietly hold everything up.",
    image: "assets/photo-boardroom.png",
  },
  {
    id: "transfer-pricing",
    category: "Taxation",
    date: "14 May 2026",
    read: "7 min read",
    author: "Olanrewaju Jolaoso",
    title: "Transfer pricing at the Tax Appeal Tribunal — lessons from the last cycle",
    excerpt: "Recent FIRS activity signals a more assertive posture on intra-group pricing. What multinationals operating in Nigeria should be documenting before an audit lands.",
    image: "assets/photo-court.png",
  },
  {
    id: "company-secretarial",
    category: "Corporate & Commercial",
    date: "30 April 2026",
    read: "4 min read",
    author: "Temitope Odeyinka",
    title: "The company secretary as risk control, not paperwork",
    excerpt: "Statutory filings are where governance either holds or quietly erodes. Why the secretarial function deserves a seat closer to the board.",
    image: "assets/photo-lawyer.png",
  },
];
